version: "3"

services:
    nginx:
        image: yansongda/docker-nginx
        ports:
            - "80:80"
        volumes:
            - ./data/www:/www
        links:
            - php
        depends_on:
            - php
    php:
        image: yansongda/docker-php7-fpm
        volumes:
            - ./data/www:/www
        expose:
            - "9000"
        depends_on:
            - mariadb
            - redis
            - memcached
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yansongda
        volumes:
            - ./data/mariadb:/var/lib/mysql
        expose:
            - "3306"
    redis:
        image: redis
        volumes:
            - ./data/redis:/data
        expose:
            - "6379"
    memcached:
        image: memcached
        expose:
            - "11211"